fix: fixed typo in error message (#120)
## Description
One-line change fixing a typo in an error message.

## What problem does this change solve?
There was a typo, meaning that if there was a missing parameter, instead
of raising a `ValueError` and displaying the error message "Missing
component...", an AttributeError would be raised: `AttributeError:
'GroupByParam' object has no attribute 'group'. Did you mean: 'groups'?`

By opening this pull request, I affirm that all authors agree to the
[Contributor License
Agreement.](https://github.com/ecmwf/codex/blob/main/Legal/contributor_license_agreement.md)